fix link to dashboard
the /ui redirect assumes dashboard is running on https and gives the
following since the version of dashboard used here does not do https:

/ui redirects to /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.192.2.1:9090/'
```

since the /ui redirect is scheduled to go away in 1.10 it makes sense to
just link to the actual dashboard itself at
"http://localhost:8080/api/v1/namespaces/kube-system/services/kubernetes-dashboard:/proxy".